### ISSUE TITLE
As a logged in user, I want to start a lobby from the main menu for a PvP mode game. I can click on “create lobby” in the main menu and start a lobby for up to 6 players. This allows me to initiate a PvP lobby and ultimately game.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#10]
- [x]  sopra-fs23-group-29/sopra-fs23-group-29-client#91
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#38
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#39
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#40
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#41
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#26
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#27
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#52
