### ISSUE TITLE
As a logged in user, who created a PvP lobby, I want to be able to invite registered users to my lobby. There should be a button “invite user” which allows me to invite registered users. I want this to be able to invite my friends to play with me.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#11]
- [ ] sopra-fs23-group-29/sopra-fs23-group-29-client#42
- [ ] sopra-fs23-group-29/sopra-fs23-group-29-client#43
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#44
