### ISSUE TITLE
As a logged in user, I want to be able to join a free lobby in order to participate in a PvP game.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#12]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#45
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#94
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#95
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#103
