### ISSUE TITLE
As a logged in user, I want to be able to display all open lobbies which I can join. If a lobby is joinable (not full), there should be a button “join”. Each lobby should show the number of free/occupied slots.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#13]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#96
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#47
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#48
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#36
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#37
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#38
