### ISSUE TITLE
As a logged in user, I have opened a PvP mode lobby from the main menu. At least one player has joined my lobby. The game has been started because all players ticked the box “ready”.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#14]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#49
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#50
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#51
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#28
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#29
