### ISSUE TITLE
When all players of the round have made their moves, I want to see the result of the placed markers and the corresponding results on the game board in order to finish the turn.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#17]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#60
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#61
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#62
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#63
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#98
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#99
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#59
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#60
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#117
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#118
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#67
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#125
