### ISSUE TITLE
I (and all possible other players) ended our turns, the game calculated for each player how many field his piece will move forward. One by one, I want to see for each player the movement of his piece. Possible barriers in the path are resolved by each player.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#18]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#64
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#65
- [ ] sopra-fs23-group-29/sopra-fs23-group-29-client#66

**Comment by mwooll** [comment]
Resolved with commit:
[the movement of the players is now as expected, ...](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/commit/290cc6a4b05a92e4ff7eefc71d7e237aafdaf80d) on client
