### ISSUE TITLE
As a user after calculating the turn results, I want to be posed a barrier question in case my game piece hits a barrier question. I have to answer the barrier question in order to move on.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#19]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#67
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#68
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#69
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#69 
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#70

**Comment by mwooll** [comment]
Resolved since all the tasks are resolved
