### ISSUE TITLE
As a player, when any player in a game reaches the winning conditions, I want the game to end. A final ranking pops up and there is a button “Back to Main Menue”.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#20]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#70
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#71
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#72
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#100
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#115
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#116
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#64
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#65
