### ISSUE TITLE
As a player, I want to be able to leave a game in lobby or progress if I don’t want to play anymore.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#22]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#75
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#76
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#77
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#50
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#51
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#63
- [x] sopra-fs23-group-29/sopra-fs23-group-29-server#66
