### ISSUE TITLE
As a logged in user, I want to be able to start a Solo mode game from the main menu and set options. This allows me to set up a Solo mode game in the way I want to play.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#8]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#30
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#31
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#32
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#33
