### ISSUE TITLE
As a logged in user, I have started a Solo mode game from the main menu and have chosen appropriate options. I want to be able to click on the "Start" button, upon which a Solo mode game starts in order to play the game.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-server#9]
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#34
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#35
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#36
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#37
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#133
- [x] sopra-fs23-group-29/sopra-fs23-group-29-client#134
